### ISSUE TITLE
How to build custom tokenizer?

### ISSUE THREAD

**Issue by snunez1** [jolby/cl-tokenizers#6]
I am porting Karpathy's [llama2.c](https://github.com/karpathy/llama2.c/tree/master) to Common Lisp and have reached the point where I need to encode/decode byte pairs.

In his example he uses a limited vocabulary of 256 words. I could port the [BPE tokenizer in the repository](https://github.com/karpathy/llama2.c/blob/350e04fe35433e6d2941dce5a1f53308f87058eb/run.c#L365), but this seems like a duplication of effort, and that it may be better to extend `cl-tokenizers` instead.

Some specific challenges in this case:

- The tokenizer binary file needs to be read from disk instead of a URL.  Perhaps reading tokenizer files should be made generic to accept a stream so that they can be read from anywhere.
- This binary format places the `max-token-length` as the first f32 integer in the file.  It seems that many tokenizer files are going to have custom binary formats and it would be nice if we had an easy way to cater for them.

For binary model files, I am using a fork of [binary-types](https://github.com/snunez1/binary-types) library for these custom formats.  Perhaps this will be useful here?

**Comment by jolby** [comment]
Hi Steve,

That's great you're porting llama2.c! That will be a nice addition for the CL community.

One of my goals for the project was to be able to support different types of tokenizers. Maybe we could try to surface generic BPE vocabulary loading related functionality to the protocols.lisp file? I'd be happy to try to accommodate your use case. If you have further ideas comment here or you could sketch out some code changes in a pull request.

**Comment by snunez1** [comment]
I think this is the right approach.  All tokenizers are going to need `encode` and `decode`, but the mechanisms behind them will change.  Still, it seems that a lot of the various tokenizer parts could be abstracted to common data structure (?).

For porting llama2.c, we need [encode](https://github.com/karpathy/llama2.c/blob/350e04fe35433e6d2941dce5a1f53308f87058eb/run.c#L452) and [decode](https://github.com/karpathy/llama2.c/blob/350e04fe35433e6d2941dce5a1f53308f87058eb/run.c#L418) for the input prompt and generated text.

If my theory that we can abstract most of a data structure to represent tokenizers is correct, then we could have a subclass for each specific type, along with a custom reader/writer for the binary format.

That's one rough sketch of how we can add additional tokenizers.  For this specific port we need to [build a tokenizer](https://github.com/karpathy/llama2.c/blob/350e04fe35433e6d2941dce5a1f53308f87058eb/run.c#L385) from  Karpathy's binary format ([tokenizer.bin](https://github.com/karpathy/llama2.c/blob/350e04fe35433e6d2941dce5a1f53308f87058eb/tokenizer.bin)) for mini-stories and implement `encode` and `decode`.

**Comment by jolby** [comment]
Hi Steve,

I've made a small marker change to the protocols.lisp file to indicate we can encode/decode things other than text. It will be up to the implementer to specialize based on what their requirements are. If you need anything else to allow you to proceed with the porting of the llama2c encoder/decoder let me know. Once you've got the specific machinery working, we can look at factoring out a base encoder class or mixin. Does that sound good?

**Comment by jolby** [comment]
Also, If we need to expand the protocol signatures to have &rest, &key, &allow-other-keys to help implementers configure the encoder/decoder with implementation specific parameters we can do that as well.

**Comment by snunez1** [comment]
> Hi Steve,
> 
>... If you need anything else to allow you to proceed with the porting of the llama2c encoder/decoder let me know. Once you've got the specific machinery working, we can look at factoring out a base encoder class or mixin. Does that sound good?

My hope was that you would run with the tokenizers in Lisp.  Working with LLMs is far too labour intensive for one man to do and we need specialisation.  I haven't got the time for a major detour; learning and modifying `binary-types` sucked up _way_ more time than I had anticipated.

Are you able to implement encode/decode for the llama2.c tokenizer?

**Comment by jolby** [comment]
Definitely not right now! I was under the impression that you were doing the porting of llama2.c.  I have other work and personal projects I'm working on and like you, I don't have time for a major detour.  I'll close this issue now, and if someone starts to work on a llama2c encoder we can reopen or another issue can be created.
